Better sights
Urban-Coalition/ArcCW_UD pull request #30
Opened 2022-08-13 21:44 UTC by VolatileIvory

Same thing as UR, just made sights comfortably distanced from the camera.

2022-08-17 02:35 UTC, VolatileIvory commented
Gave the M1014 grip stock stats just because, and made it and the sporting stock have slightly fancier titles. Because why not.

2022-12-13 20:29 UTC, TheOnly8Z requested changes

2022-12-13 20:29 UTC, TheOnly8Z commented on lua/weapons/arccw_ud_m1014.lua
> +            {s = path2 .. "usas_chback.ogg", t = 0.8},
Looks like a sound from the deprecated USAS - Is it appropriate here?

2022-12-13 20:29 UTC, TheOnly8Z commented on lua/arccw/shared/attachments/ud_m16_stock_moe.lua
> +att.PrintName = "Magpul MOE Stock"
Real brand should only show up with true names on. Please keep as AMCAR for consistency across M16 attachments and set true name to MAGPUL (upper case)

2022-12-13 20:29 UTC, TheOnly8Z commented on lua/arccw/shared/attachments/ud_m1014_stock_sport.lua
> +att.PrintName = "M4 Semi-Grip Fixed Stock"
Use true names only when truename convar is set.

2022-12-20 22:22 UTC, Fesiug commented
If you are still developing this, join the Discord and talk with us there

2022-12-20 22:22 UTC, closed without merging